// PDF export using jsPDF + autoTable
export async function exportResultPDF({ type, result, courses, semesters, semesterNumber }) {
  const { jsPDF } = await import("jspdf");
  await import("jspdf-autotable");

  const doc = new jsPDF();
  const primary = [0, 84, 166]; // Sukkur IBA blue

  // Header
  doc.setFillColor(...primary);
  doc.rect(0, 0, 210, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Sukkur IBA University", 14, 13);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`${type === "gpa" ? "GPA" : "CGPA"} Calculator Result`, 14, 22);

  // Date
  doc.setTextColor(180, 180, 180);
  doc.setFontSize(9);
  doc.text(new Date().toLocaleDateString("en-PK", { dateStyle: "long" }), 196, 22, { align: "right" });

  // Summary card
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");

  if (type === "gpa") {
    doc.text(`Semester ${semesterNumber} GPA Report`, 14, 42);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.text(`GPA: ${result.gpa.toFixed(2)} / 4.00`, 14, 52);
    if (result.percentage !== null) doc.text(`Percentage: ${result.percentage.toFixed(2)}%`, 14, 60);
    doc.text(`Total Credit Hours: ${result.totalCreditHours}`, 14, 68);
    doc.text(`Failed Courses: ${result.failedCourses}`, 14, 76);

    // Course table
    const rows = result.processedCourses.map((c, i) => [
      i + 1,
      c.name || `Course ${i + 1}`,
      c.creditHours,
      c.isNonCredit ? "Non-Credit" : "Credit",
      c.marks !== "" && c.marks !== undefined ? `${c.marks}%` : "—",
      c.resolvedGrade,
      c.resolvedGP.toFixed(2),
      c.isNonCredit ? "—" : c.weightedPoints.toFixed(2),
    ]);

    doc.autoTable({
      startY: 86,
      head: [["#", "Course", "CH", "Type", "Marks", "Grade", "GP", "Weighted"]],
      body: rows,
      headStyles: { fillColor: primary },
      alternateRowStyles: { fillColor: [245, 248, 255] },
      styles: { fontSize: 9 },
    });
  } else {
    doc.text("CGPA Report", 14, 42);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.text(`CGPA: ${result.cgpa.toFixed(2)} / 4.00`, 14, 52);
    doc.text(`Total Credit Hours: ${result.totalCredits}`, 14, 60);

    const rows = semesters.map((s, i) => [
      i + 1,
      s.label || `Semester ${i + 1}`,
      parseFloat(s.gpa).toFixed(2),
      s.creditHours,
      (parseFloat(s.gpa) * parseFloat(s.creditHours)).toFixed(2),
    ]);

    doc.autoTable({
      startY: 72,
      head: [["#", "Semester", "GPA", "Credit Hours", "Weighted Points"]],
      body: rows,
      headStyles: { fillColor: primary },
      alternateRowStyles: { fillColor: [245, 248, 255] },
      styles: { fontSize: 10 },
    });
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by Sukkur IBA GPA Calculator — For reference only", 14, 290);
    doc.text(`Page ${i} of ${pageCount}`, 196, 290, { align: "right" });
  }

  doc.save(`Sukkur_IBA_${type.toUpperCase()}_Report.pdf`);
}
